apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - image: locustio/locust
        imagePullPolicy: Always
        name: locust-master-container
        args: ["--master"]
        volumeMounts:
          - mountPath: /home/locust
            name: locust-scripts
        ports:
        - containerPort: 5557
          name: comm
        - containerPort: 5558
          name: comm-plus-1
        - containerPort: 8089
          name: web-ui
      restartPolicy: Always
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm

---

apiVersion: v1
kind: Service
metadata:
  name: locust-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP
      name: http
    - port: 5557
      name: communication
      protocol: TCP
    - port: 5558
      name: communication-plus-1
      protocol: TCP
  selector:
    app: locust-master