apiVersion: v1
kind: Namespace
metadata:
  name: locust

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - image: locustio/locust
        imagePullPolicy: Always
        name: locust-master-container
        #Available locustfiles: /home/locust/funkyflask/funkyflasklocustfile.py, /home/locust/flaskdatabase/pythonDbLocustfile.py, null (for petclinic) values have to be adjusted in slave as well
        args: ["--master", "--locustfile", "/home/locust/funkyflask/funkyflasklocustfile.py"]
        volumeMounts:
          - mountPath: /home/locust
            name: locust-scripts
          - mountPath: /home/locust/funkyflask
            name: funkyflask-locust
          - mountPath: /home/locust/flaskdatabase
            name: flaskdatabase-locust
        ports:
        - containerPort: 5557
          name: comm
        - containerPort: 5558
          name: comm-plus-1
        - containerPort: 8089
          name: web-ui
      restartPolicy: Always
      volumes:
      - name: locust-scripts
        configMap:
          name: petclinic-scripts-cm
      - name: funkyflask-locust
        configMap:
          name: funkyflask-scripts-cm
      - name: flaskdatabase-locust
        configMap:
          name: databaseflask-scripts-cm

---

apiVersion: v1
kind: Service
metadata:
  name: locust-load-balancer
  namespace: locust
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP
      name: http
  selector:
    app: locust-master

---

apiVersion: v1
kind: Service
metadata:
  name: locust-internal
  namespace: locust
spec:
  type: ClusterIP
  ports:
    - port: 5557
      name: communication
      protocol: TCP
    - port: 5558
      name: communication-plus-1
      protocol: TCP
  selector:
    app: locust-master