apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
  namespace: locust
data:
  locustfile.py: |
    from locust import HttpUser, task

    class HelloWorldUser(HttpUser):
      @task
      def hello_world(self):
          self.client.get("/")
          self.client.get("/owners/find")
          self.client.get("/owners?lastName=")
          self.client.get("/vets.html")