apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - image: locustio/locust
        imagePullPolicy: Always
        name: locust-worker-container
        args: ["--worker", "--master-host=locust-load-balancer"]
        volumeMounts:
          - mountPath: /home/locust
            name: locust-scripts
      restartPolicy: Always
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm