apiVersion: v1
kind: Pod
metadata:
  name: pythondb-pod
spec:
  restartPolicy: Never
  initContainers:
    - name: busybox
      image: busybox:1.28
      command: 
      - /bin/sh
      - -c
      - 'until nc -z sz-mysql-service 3306; do echo waiting for mysql; sleep 5; done;'
  containers:
  - name: pythondb-pod-container
    image: us-central1-docker.pkg.dev/playground-s-11-8aaf1fd2/my-repository/pythondb:v1
    imagePullPolicy: Always
    command:
    - /bin/bash
    - -c
    - 'pythondb -u 200000'