apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sz_mysql
  template:
    metadata:
      labels:
        app: sz_mysql
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-volumeclaim
      containers:
      - name: sz-mysql
        image: us-central1-docker.pkg.dev/playground-s-11-049ae63a/my-repository/sz_mysql:v1
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /volume
          name: mysql-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility
  template:
    metadata:
      labels:
        app: utility
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-volumeclaim
      containers:
      - name: utility
        image: us-central1-docker.pkg.dev/playground-s-11-049ae63a/my-repository/utility:v1
        volumeMounts:
        - mountPath: /volume
          name: mysql-storage
---

apiVersion: v1
kind: Service
metadata:
  name: sz-mysql-service
spec:
  selector:
    app: sz_mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Pod
metadata:
  name: pythondb-pod
spec:
  initContainers:
    - name: busybox
      image: busybox:1.28
      command: 
      - /bin/sh
      - -c
      - 'until nc -z sz-mysql-service 3306; do echo waiting for mysql; sleep 2; done;'
  containers:
  - name: pythondb-pod-container
    image: us-central1-docker.pkg.dev/playground-s-11-049ae63a/my-repository/pythondb:v1
    imagePullPolicy: Always
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
