apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sz_mysql
  template:
    metadata:
      labels:
        app: sz_mysql
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-volumeclaim
      containers:
      - name: sz-mysql
        image: us-central1-docker.pkg.dev/playground-s-11-8aaf1fd2/my-repository/sz_mysql:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /volume
          name: mysql-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility
  template:
    metadata:
      labels:
        app: utility
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-volumeclaim
      containers:
      - name: utility
        image: us-central1-docker.pkg.dev/playground-s-11-8aaf1fd2/my-repository/utility:v1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /volume
          name: mysql-storage
---

apiVersion: v1
kind: Service
metadata:
  name: sz-mysql-service
spec:
  selector:
    app: sz_mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
