apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: us-central1-docker.pkg.dev/playground-s-11-a82c7afb/my-repository/javabuilder:v1
    env:
      - name: auth_token
        value: myvalue
    command: ["/bin/sh", "-c"]
    args: ["./mvnw package; echo 'Second Command'; sleep 3600"]
    #command: ["./mvnw","package"]