apiVersion: v1
kind: Namespace
metadata:
  name: data-loader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-deployment
  namespace: data-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility
  template:
    metadata:
      labels:
        app: utility
    spec:
      containers:
      - name: utility
        image: us-central1-docker.pkg.dev/playground-s-11-3b88a7ff/my-repository/utility:v1
        imagePullPolicy: Always