apiVersion: batch/v1
kind: Job
metadata:
  name: javabuilder
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: javabuilder
        image: us-central1-docker.pkg.dev/playground-s-11-b0185069/my-repository/javabuilder:v1
        imagePullPolicy: Always
        env:
          - name: auth_token
            value: ya29.a0AcM612zOTxW0DRKbvgvlur2qA38zwxFVZE2neA72qntCKY-7Q6KEoZ35RVRvxTWNsgi9KG7RcnCFpLHgFivUWhUZhpVX01ZgsfbNaOcFZR9Sn_TYaNuaSc0x_LXUs7HmC4X3p-XRWi63AT-1n79itjlja10wbEeg0_KcafMjVmE2QtRcdEZG26G_4xaL3Aq6k2GSezQcXG9hFqy8awmw6iQPYIR35Yc-MauEIXZLM8ZYmZFI_7YAOGsmhzXKy4rN23VUGhH8GRwAlSXMZ9XcONz3cU3VQytMbi-cYXNzLeqlUMTiLwavmntzdhoyIT8yizPhONtMfixHc6xzN3S7OrcxuzgAVTuhyibGDiZ_SHLPhFKtESWQX4RZpmJkl0HT9UwYCkanIlVywPdFex3vvzz47CHObNh3aCgYKAU4SARESFQHGX2MiLEZgq4H310QjiEwp0c5q8w0423
        command: ["/bin/sh", "-c"]
        args: ["./mvnw package; curl -X POST --data-binary @target/spring-petclinic-3.2.0-SNAPSHOT.jar -H \"Authorization: Bearer $auth_token\" -H \"Content-Type: application/octet-stream\" https://storage.googleapis.com/upload/storage/v1/b/playground-s-11-b0185069-sz-storage/o?name=petclinicapp.jar"]