apiVersion: v1
kind: Pod
metadata:
  name: javabuilder
spec:
  containers:
  - name: javabuilder
    image: us-central1-docker.pkg.dev/playground-s-11-152ef87f/my-repository/javabuilder:v1
    imagePullPolicy: Always
    env:
      - name: auth_token
        value: null
    command: ["/bin/sh", "-c"]
    args: ["./mvnw package; echo 'Second Command'; curl -X POST --data-binary @target/spring-petclinic-3.2.0-SNAPSHOT.jar -H \"Authorization: Bearer $auth_token\" -H \"Content-Type: application/octet-stream\" https://storage.googleapis.com/upload/storage/v1/b/playground-s-11-152ef87f-sz-storage/o?name=petclinicapp.jar ; sleep 3600"]
    #command: ["./mvnw","package"]