apiVersion: v1
kind: Pod
metadata:
  name: javabuilder
spec:
  containers:
  - name: javabuilder
    image: us-central1-docker.pkg.dev/playground-s-11-77b1707a/my-repository/javabuilder:v1
    imagePullPolicy: Always
    env:
      - name: auth_token
        value: ya29.a0Ad52N3-PjGJ3LIRNec6SrEKIEEj6VzKWZ4I94g91STI9lr8rIRYHBLQEsoLJN_HHs7MypA7BUudoQ_UMOeBPbsNifuhfccY_gjnBnncJ1JgEJT-5T8CYDx2Dl2YmqKpN7YbkBzSVKDhhxzhgFh4b53QXU5HBXI6pxcVzAfa-IbpbVYuy_2lVslxiOOn6KKJ9hrkfQgqvEdt_no4JXbHmBlcYCLHTz4EhbLlFOiCbVPtK1ZDRRLlX6nwlA-Lgp881-VsPZD6UJf0eNlnyFpIcmdCsd9epqz35TNOGyvk75D9PFDPtWVRiURKDGSNaMMdSxtMQk00abHjt8dV_o4J0nch9G64w_yi-y_uIqu0_Zm5fV2waCkK6bmLALoQKReWtvFlysEsId_Jd7ZuiKSw4T50C6siXEm4aCgYKAf4SARASFQHGX2MivYy4XnDDKs0iu7xksAoY6g0422
    command: ["/bin/sh", "-c"]
    args: ["./mvnw package; echo 'Second Command'; curl -X POST --data-binary @target/petclinic.war -H \"Authorization: Bearer $auth_token\" -H \"Content-Type: application/octet-stream\" https://storage.googleapis.com/upload/storage/v1/b/playground-s-11-77b1707a-sz-storage/o?name=petclinicapp.war ; sleep 3600"]
    #command: ["./mvnw","package"]