apiVersion: batch/v1
kind: Job
metadata:
  name: javabuilder
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: javabuilder
        image: us-central1-docker.pkg.dev/playground-s-11-2953e6ff/my-repository/javabuilder:v1
        imagePullPolicy: Always
        env:
          - name: auth_token
            value: ya29.a0AcM612yBEErqZDVDFErxaMo3hTCtDkICjDgGsvTfnkzfE531PTuVqm0EZYZhjC0LN5X76Y1T8W45Wsa0Nu1iNlfLRH46RwnnVe1UvAQQlC4sNcy1mNJipuvbVq0XqeKPcWMDlq-QCHiFiAs3G816h3bpXbaiQWpoL89hVnCtmj6h7RKGDwzhO8PW3hEU0zaz74M9v2mlvQ5WnOHlUqJKn4zS4YIngEXoH8ILIaOslS5vrQmJhBTI_stgLg37B7H44W9EkW5JPheH6Oxe-QZ-xqMwcugr-9mYmvIDckzvaooGR49qK4avNMvNj2S17XL5U9LNo-J85Hki7T6wdWpqCA_96_3ryFuBJ_4YOERB2ChEGzgDPLDj7iaYt4S5tU6nAWAEnoG-P9rkuy_2zCTzrKQeqbvXawaCgYKAc0SARMSFQHGX2MinKkZzvwdXpaWpR6JCk0l-A0421
        command: ["/bin/sh", "-c"]
        args: ["./mvnw package; echo 'Second Command'; curl -X POST --data-binary @target/spring-petclinic-3.2.0-SNAPSHOT.jar -H \"Authorization: Bearer $auth_token\" -H \"Content-Type: application/octet-stream\" https://storage.googleapis.com/upload/storage/v1/b/playground-s-11-2953e6ff-sz-storage/o?name=petclinicapp.jar"]