apiVersion: batch/v1
kind: Job
metadata:
  name: javabuilder
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: javabuilder
        image: us-central1-docker.pkg.dev/playground-s-11-d9ce345b/my-repository/javabuilder:v1
        imagePullPolicy: Always
        env:
          - name: auth_token
            value: ya29.a0Ad52N39hiy4qEbgYsYZMrZZq8Fi2m3o5zSGCEQl-7ATaJ0qZY79JihgvE6MRYETKlF5Tt4FWsfyetY5TyT44KMPd6C-D7U94HIIkllWYDKuMk7UqBqbXo5xzN5mW-_o6flWu4XPQJkHKC20vQsYq8Ihzu5yh-W-WIZl54Y0vZfjqLBqGbXKcRV7VLrHyDxXVgUlEsBccuzu1PKDhqXiYl4VINab7QFzKmrT_YsbwcWDIQUZaq84wxmYYYUwW1_m-4I8-HeYnqFha71pk_eftki3OrPneuzaluUK1W2pf6ljA2Fah9nuuD0dlzCAJsSw8e8EHtOpX2VaU-wGKmZFGe90kGG311ki74sp6k4iJc2AITGUA6OiSHH0b-vXVxLcKKvOi21kxDhk43AZqy_pgiOOkZcHe9QaCgYKAXUSARESFQHGX2MiNA7EdA86e9ndMXMIZd7VtQ0421
        command: ["/bin/sh", "-c"]
        args: ["./mvnw package; echo 'Second Command'; curl -X POST --data-binary @target/spring-petclinic-3.2.0-SNAPSHOT.jar -H \"Authorization: Bearer $auth_token\" -H \"Content-Type: application/octet-stream\" https://storage.googleapis.com/upload/storage/v1/b/playground-s-11-d9ce345b-sz-storage/o?name=petclinicapp.jar"]