apiVersion: v1
kind: Namespace
metadata:
  name: data-loader

---

apiVersion: batch/v1
kind: Job
metadata:
  name: pythondb-job
  namespace: data-loader
spec:
  parallelism: 12
  completions: 96
  template:
    metadata:
      name: pythondb-pod
    spec:
      restartPolicy: Never
      containers:
        - name: pythondb-container
          image: us-central1-docker.pkg.dev/playground-s-11-77b1707a/my-repository/pythondb:v1
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
            - 'pythondb -u 25000'