FROM ubuntu:22.04

RUN apt-get update -y
RUN apt-get install curl pip python3-venv -y
ENV FLASK_APP SimpleApp.py
ENV FLASK_ENV development
COPY . /home/project
RUN python3 -m venv /app/venv
RUN /app/venv/bin/pip install -r /home/project/source/requirements.txt
WORKDIR /home/project/source
EXPOSE 5000

CMD [ "/app/venv/bin/python", "/home/project/source/SimpleApp.py" ]